services:
  db:
    image: postgres:latest
    env_file:
      - .env
    # volumes:
    #   - ./setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_DB=${POSTGRES_DB} 
      - ADMINER_DEFAULT_SERVER=${POSTGRES_SERVER}
      - ADMINER_DEFAULT_USERNAME=${POSTGRES_USER}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php

  shelved:
    build:
      context: ./src
      dockerfile: dockerfile
      # args:
      #   ENV: dev
    container_name: shelved
    env_file:
      - .env
    environment:
      - ENV=development
    volumes:
      - ./src/app:/src/app
      - ./src/views:/src/views
      - ./src/db:/src/db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'driver' => $$_ENV['ADMINER_DEFAULT_DRIVER'],
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'db'    => $$_ENV['ADMINER_DEFAULT_DB'],
          ];
        }
        include './adminer.php';
      ?>
